export default {
    main: `relative block overflow-x-clip`,
    content_container: `relative left-[50%] translate-x-[-50%] max-w-[1024px] w-full flex flex-wrap py-[100px] ` +
        `px-[30px] -lg:pt-[40px] -lg:pb-[80px]`,
    content_left: `w-full lg:w-[50%] lg:sticky lg:top-[100px] block lg:self-start`,
    content_right: `relative w-full lg:w-[calc(50%_-_40px)] lg:pl-[20px] -lg:text-center`,
    image: `w-[296px] h-[414px] object-cover`,
    image_container: `flex justify-center gradient-backdrop-long`,
    name: `w-full -lg:flex-col -lg:justify-center -lg:items-center`,
    squiggly: `my-[10px]`,
    career_title: `heading-4 block my-[10px]`,
    h1: `block heading-1`,
    time: `mb-[40px]`,
    time_item: `heading-5 inline`,
    content: ``,
    callouts: ``,
    btn_container: ``,
    btn_content: `block mt-[40px] mb-[20px]`,
    btn_left: `btn-box btn-box-dark`,
    btn_right: `btn-box btn-box-blue`,
    all_faculty: `block w-full mt-[40px] mb-[80px]`,
}