export default {
    main: `relative block w-full cover py-[40px] lg:py-[80px] -xl:px-[30px] overflow-x-clip`,
    content_container: `w-full grid grid-cols-1 lg:grid-cols-6 gap-0 lg:gap-[60px] grid-large`,
    content_wrap: `w-full flex flex-col p-[40px] pt-0 bg-black text-blue-light mb-[20px]`,
    form_container: `col-span-4 flex flex-col -lg: mb-[60px]`,
    contact_info: `col-span-2`,
    intro: `w-full flex flex-col`,
    h1: `heading-2 m-0`,
    squiggly: `block self-start mt-[10px]`,
    content: `paragraph-sm max-w-[464px] mt-[20px]`,
    form: `w-full mt-[40px]`,
    contact_title: `uppercase mt-[40px]`,
    address: ``,
    contact_item: ``,
    anchor: `inline-block`,
    studio_hours: `mt-[20px]`,
    gradients: ``,
}