export default {
    main: `relative bg-white my-[40px] py-[20px] px-[30px] border-black border-[2px]`,
    item: `my-[10px] px-[20px] py-[10px]`,
    sub_item: `my-[10px]`,
    inner_block: `my-[20px] py-[20px] px-[30px] border-black border-[2px]`,
    flex: `flex flex-wrap`,
    flex_end: `w-full flex justify-end`,
    flex_full: `w-full`,
    flex_6: `w-[50%] -lg:w-full`,
    flex_4: `w-[33%] -lg:w-full`,
    flex_3: `w-[25%] -lg:w-full`,
    mx_sm: `mx-[10px]`,
    my_sm: `my-[10px]`,
    mt_sm: `mt-[10px]`,
    mb_sm: `mb-[10px]`,
    pt_sm: `pt-[10px]`,
    pb_sm: `pb-[10px]`,
    mx_md: `mx-[20px]`,
    my_md: `my-[20px]`,
    mt_md: `mt-[20px]`,
    mb_md: `mb-[20px]`,
    pt_md: `pt-[20px]`,
    pb_md: `pb-[20px]`,
    text_alert: `!text-[red]`,
    button: `border-blue-light border-[1px] bg-black text-blue-light text-[14px] py-[10px] px-[20px] rounded-[10px]`,
    button_remove: `border-[red] border-[1px] bg-[red] text-white text-[14px] py-[10px] px-[20px] rounded-[10px]`,
    button_save: `border-blue border-[1px] bg-blue text-white text-[14px] py-[10px] px-[20px] rounded-[10px]`,
    image: `!max-w-[300px] mb-[10px] rounded-[10px]`,
    image_small: `w-full mb-[10px] md:!h-[250px] lg:!h-[150px] object-cover rounded-[10px]`,
    repeater_item: `w-full lg:w-[calc(33.33%_-_20px)] mx-[10px] my-[20px] box-border bg-blue-light text-black p-[10px] rounded-[10px]`,
    postSelect: {
        main: `w-full !max-h-[400px] overflow-scroll flex-col list-none m-0 px-10 py-4 [&>li]:flex [&>li]:items-center [&>li]:justify-between [&>li]:w-full [&>li]:cursor-pointer ` + 
            `border-black border-solid border-[2px] rounded-[10px] [&>li]:relative`,
        selected: `[&>h4]:text-blue [&>img]:border-blue`,
        image: `w-[40px] !h-[40px] object-cover object-top border-black border-solid border-[2px]`,
        title: `heading-3 inline-block ml-[10px] my-[10px] hover:text-blue`,
        index: `absolute right-[-20px] top-[2px] text-2xl font-bold text-blue-light z-2`,
    },
}