export default {
    main: `relative block`,
    content_container: `relative left-[50%] translate-x-[-50%] max-w-[1024px] w-full flex flex-wrap py-[100px] ` +
        `px-[30px] -lg:pt-[40px] -lg:pb-[80px]`,
    content_left: `w-full lg:w-[50%] lg:sticky lg:top-[100px] block lg:self-start`,
    content_right: `relative w-full lg:w-[calc(50%_-_40px)] lg:pl-[20px] -lg:text-center`,
    image: `w-[310px] h-[310px] object-cover`,
    image_container: `flex justify-center`,
    title: `w-full -lg:flex-col -lg:justify-center -lg:items-center`,
    squiggly: `mt-[20px]`,
    date: `heading-4 block mt-[20px]`,
    h3: `block heading-3-bold`,
    time: `mb-[40px]`,
    time_item: `heading-5 inline`,
    content: ``,
    callouts: ``,
    btn_container: ``,
    btn_content: `block mt-[40px] mb-[20px]`,
    btn_left: `btn-box btn-box-dark`,
    btn_right: `btn-box btn-box-blue`,
    all_events: `block w-full text-center mt-[20px] mb-[80px]`,
}