export default {
    main: `relative block py-[80px] -xl:px-[30px] overflow-x-clip z-[-1]`,
    content_container: `w-full flex flex-wrap grid-large`,
    intro: `w-full text-center pb-[20px]`,
    title: `heading-2 !italic`,
    events_container: `w-full grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-[20px] md:gap-[40px] lg:gap-[40px] items-start`,
    event: `w-full flex flex-col justify-center items-center flex-wrap mt-[40px] md:mt-[80px] lg:mt-[40px]`,
    event_image_wrapper: `w-[300px] h-[300px] lg:w-[280px] lg:h-[280px] text-center`,
    image: `w-full h-full object-cover relative p-[10px]`,
    event_content: `relative w-full flex flex-col`,
    content_wrap: `w-full flex flex-col items-center text-center`,
    h3: `heading-4 mt-[60px]`,
    date: `heading-6 block py-[20px]`,
    p: `-lg:max-w-[400px]`,
    event_link: `link text-black block mt-[20px]`,
    all_events: `w-full text-center`,
    squiggly: `mt-[20px]`,
}