export default {
    main: `relative block py-[100px] -xl:px-[30px] overflow-clip bg-black`,
    content_container: `w-full flex flex-wrap grid-large`,
    content_wrapper: `relative w-full text-center text-white z-5`,
    intro: `w-full text-center pb-[40px]`,
    title: `heading-2 !italic`,
    bios_container: `w-full grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-[40px] xl:gap-[60px]`,
    bio: `w-full block flex flex-col items-center lg:w-[296px] my-[20px]`,
    bio_image_wrapper: `relative w-[296px] h-[414px] z-10`,
    image: `w-full h-full object-cover relative p-[10px]`,
    bio_content: `relative w-full`,
    content_wrap: `w-full -lg:flex -lg:flex-col -lg:items-center -lg:text-center text-white z-5`,
    h3: `heading-4 mt-[40px]`,
    career_title: `italic font-bold block my-[20px]`,
    p: ``,
    bio_link: `btn-default btn-white-blue block mt-[20px]`,
    all_bios: `w-full text-center mt-[80px] mb-[20px]`,
    gradient: `text-radial-gradient text-radial-gradient-center z-1`,
}